config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :categories
  resources :sources
  resources :users

  root 'home#index'
  get '/about', to: 'about#index'
  get '/search', to: 'search#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/source.rb
class Source < ApplicationRecord
    has_many :quotes, dependent: :nullify

    # function to concatenate first and last name of source, seperated by a space
    def full_name
        [fname, lname].join(' ')
    end

    # First name validation, checking if present, max length, and only letters
    validates :fname, presence: { message: ": First Name can't be blank" },
        length: { maximum: 30, too_long: ": %{count} characters is the maximum allowed for the source's First Name" },
        format: { with: /\A[a-zA-Z]+\z/, message: ": First Name only allows letters" }

    # Last name validation, checking max length, and only letters
    validates :lname, length: { maximum: 30, too_long: ": %{count} characters is the maximum allowed in the source's Last Name" },
        format: { with: /\A[a-zA-Z]+\z/, message: ": Last Name only allows letters" }, allow_blank: true

    # Birth and Death year validations, checking if year is valid
    validates :byear, format: { with: /\A(\d+|\d+\s*BC)\z/, message: ": Birth Year must be a valid year or a valid year in BC" }, allow_blank: true
    validates :dyear, format: { with: /\A(\d+|\d+\s*BC)\z/, message: ": Death Year must be a valid year or a valid year in BC" }, allow_blank: true

    # Bio validation, checking if the bio is too long
    validates :bio, length: { maximum: 500, too_long: ": %{count} characters is the maximum allowed for a biography" }, allow_blank: true
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: %i[ show edit update destroy ]

  # GET /sources or /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1 or /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources or /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to source_url(@source), notice: "Source was successfully created." }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1 or /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to source_url(@source), notice: "Source was successfully updated." }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1 or /sources/1.json
  def destroy
    @source.destroy

    respond_to do |format|
      format.html { redirect_to sources_url, notice: "Source was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def source_params
      params.require(:source).permit(:fname, :lname, :byear, :dyear, :bio)
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.erb
<%= form_with(model: source) do |form| %>
  <% if source.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
        <% source.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fname, style: "display: block" %>
    <%= form.text_field :fname %>
  </div>

  <div>
    <%= form.label :lname, style: "display: block" %>
    <%= form.text_field :lname %>
  </div>

  <div>
    <%= form.label :byear, style: "display: block" %>
    <%= form.text_field :byear %>
  </div>

  <div>
    <%= form.label :dyear, style: "display: block" %>
    <%= form.text_field :dyear %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sources/_source.html.erb
<div id="<%= dom_id source %>">
  <p>
    <strong>Fname:</strong>
    <%= source.fname %>
  </p>

  <p>
    <strong>Lname:</strong>
    <%= source.lname %>
  </p>

  <p>
    <strong>Byear:</strong>
    <%= source.byear %>
  </p>

  <p>
    <strong>Dyear:</strong>
    <%= source.dyear %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= source.bio %>
  </p>

</div>

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= render "form", source: @source %>

<br>

<div>
  <%= link_to "Show this source", @source %> |
  <%= link_to "Back to sources", sources_path %>
</div>

app/views/sources/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sources</h1>

<div id="sources">
  <% @sources.each do |source| %>
    <%= render source %>
    <p>
      <%= link_to "Show this source", source %>
    </p>
  <% end %>
</div>

<%= link_to "New source", new_source_path %>

app/views/sources/new.html.erb
<h1>New source</h1>

<%= render "form", source: @source %>

<br>

<div>
  <%= link_to "Back to sources", sources_path %>
</div>

app/views/sources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @source %>

<div>
  <%= link_to "Edit this source", edit_source_path(@source) %> |
  <%= link_to "Back to sources", sources_path %>

  <%= button_to "Destroy this source", @source, method: :delete %>
</div>