config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :categories
  resources :sources
  resources :users

  root 'home#index'
  get '/about', to: 'about#index'
  get '/search', to: 'search#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :quotes, dependent: :destroy

    # Email validations including email, confirmation, format and unique
    validates :email, confirmation: true, if: :email_changed?, format: URI::MailTo::EMAIL_REGEXP, uniqueness: true
    validates :email_confirmation, presence: true, if: :email_changed?
    
    # Password validation, checking if password is 6-20 characters long and contains atleast one number and one letter
    validates :password, length: { in: 6..20 }, format: { with: /\A(?=.*[A-Za-z])(?=.*[0-9]).+\z/, message: "^: Password must contain atleast one letter and one number" }, 
        unless: -> { password.blank? }

    # First and Last name validation, checking if name is <30 characters and contains only letters
    validates :fname, length: { maximum: 30, too_long: ": %{count} characters is the maximum allowed in your First Name" }, format: { with: /\A[a-zA-Z]+\z/,
        message: ": First Name only allows letters" }
    validates :lname, length: { maximum: 30, too_long: ": %{count} characters is the maximum allowed in your Lirst Name" }, format: { with: /\A[a-zA-Z]+\z/,
        message: ": Lirst Name only allows letters" }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_login, except: [:new, :create]

  # GET /users or /users.json
  def index
    # @users = User.all
    if logged_in? && is_administrator?
      @users = User.all
    elsif logged_in? && !is_administrator?
      redirect_to userhome_path
    else
      flash[:error] = "You are not authorised to access this resource"
      redirect_to login_path
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.html { redirect_to login_path, notice: "Sign up successful. Please log in." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        # if user is updated by a user and is admin, go to the user details page of the user
        if logged_in? && is_administrator?
          format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        # Otherwise if updated and is not admin, go to home page of user
        elsif logged_in? && !is_administrator?
          format.html { redirect_to '/userhome', notice: "Your account was successfully updated" }
          format.json { render :show, status: :ok, location: @user }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :email_confirmation, :password, :password_confirmation, :is_admin, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- new and update user form -->
<%= form_with(model: user) do |form| %>

  <!-- Display any errors -->
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- First name field -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.text_field :fname, placeholder: 'First Name', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
  </div>

  <!-- Last name field -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.text_field :lname, placeholder: 'Last Name', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
  </div>
  <br>
  <!-- email field -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.text_field :email, placeholder: 'Email Address', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
  </div>

  <!-- email confirmation field -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.text_field :email_confirmation, placeholder: 'Confirm Email Address', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
  </div>
  <br>
  <!-- password field -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.password_field :password, placeholder: user.password_digest.present? ? 'Password set' : 'Choose a strong password', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
  </div>
  
  <!-- password confirmation field -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
  </div>

  <!-- If user is logged in as admin, show admin checkbox -->
  <div class="form-group" style="padding-bottom: 10px;">
  <% if logged_in? && is_administrator? %>
    <%= form.label :is_admin do %>
      Admin Role
    <%= form.check_box :is_admin %>
  <% end %>

  <!-- Otherwise, set admin status to false -->
  <% else %>
    <%= form.hidden_field :is_admin, value: false %>
  <% end %>
  </div>

  <!-- If user is logged in as admin, show status dropdown -->
  <div class="form-group" style="padding-bottom: 10px;">
  <% if logged_in? && is_administrator? %>
    <%= form.select :status, ['Active', 'Suspended', 'Banned'], {}, class: 'form-control' %>
  <!-- Else if user is logged in an not admin, leave status to what it was -->
  <% elsif logged_in? && !is_administrator? %>
    <%= form.hidden_field :status %>
  <!-- Otherwise if new user and not logged in, set new account to 'Active' -->
  <% else %>
    <%= form.hidden_field :status, value: "Active" %>
  <% end %>
  </div>

  <!-- If logged in, show submit button saying 'update', otherwise show submit button saying 'submit' -->
  <div class="form-group" style="padding-bottom: 10px;">
    <% if logged_in? %>
      <%= form.submit 'Update', class: 'btn btn-primary' %>
    <% else %>
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/users/_user.html.erb
<!-- User details -->

<div id="<%= dom_id user %>" class="my-4">
  
  <!-- Display first name -->
  <div class="mb-3">
    <label class="form-label"><strong>First name:</strong></label>
    <div><%= user.fname %></div>
  </div>

  <!-- Display last name -->
  <div class="mb-3">
    <label class="form-label"><strong>Last name:</strong></label>
    <div><%= user.lname %></div>
  </div>

  <!-- Display email -->
  <div class="mb-3">
    <label class="form-label"><strong>Email:</strong></label>
    <div><%= user.email %></div>
  </div>

  <!-- Account type -->
  <div class="mb-3">
    <label class="form-label"><strong>Account Type:</strong></label>
    <div>
      <% if user.is_admin %>
        <span>Administrator</span>
      <% else %>
        <span>Standard User</span>
      <% end %>
    </div>
  </div>

  <!-- User status -->
  <div class="mb-3">
    <label class="form-label"><strong>Status:</strong></label>
    <div><%= user.status %></div>
  </div>

</div>

app/views/users/edit.html.erb
<!-- Display different heading depending on whether user is admin or not -->
<div style="padding-top: 10px;">
<% if logged_in? && is_administrator? %>
  <h3>Update User Details</h3>
  <% else %>
  <h3>Update Your Details</h3>
  <% end %>
</div>

<!-- Render the user form -->
<%= render "form", user: @user %>

<!-- Provide navigation links to show all users or show user details if admin -->
<% if logged_in? && is_administrator? %>
  <div style="padding-top: 10px;">
    <%= link_to "Show user details", @user %> |
    <%= link_to "Back to users", users_path %>
  </div>
  
<!-- Otherwise, display navigation link to show user details only if standard user -->
<% elsif logged_in? && !is_administrator? %>
  <div style="padding-top: 10px;">
    <%= link_to "Back to user details", @user %>
  </div>
<% end %>

app/views/users/index.html.erb
<!-- Manage users -->

<!-- Show notices if any -->
<p style="color: green"><%= notice %></p>

<h3>Manage Users</h3>

<!-- For each user, show a card with their first name, last name, email, status and manage user button -->
<div id="users">
  <% @users.each do |user| %>
    <div class="user card mb-4">
      <div class="card-body">
        <p class="card-text"><span style="font-weight: 600;">First Name:</span> <%=user.fname %></p>
        <p class="card-text"><span style="font-weight: 600;">Last Name:</span> <%=user.lname %></p>
        <p class="card-text"><span style="font-weight: 600;">Email:</span> <%=user.email %></p>
        <p class="card-text"><span style="font-weight: 600;">Status:</span> <%=user.status %></p>
        <a href="<%= user_path(user) %>" class="btn btn-primary">Manage User</a>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<!-- User sign up page -->

<h4 style="padding-top:10px;">
Sign up for an account - its free!
</h4>

<!-- Render new user form -->
<%= render "form", user: @user %>

app/views/users/show.html.erb
<!-- Display notification messages -->
<p style="color: green"><%= notice %></p>

<!-- render user details -->
<%= render @user %>

<!-- If user is logged in and is either an admin, or the account owner: -->
<% if logged_in? && (is_administrator? || current_user.id == @user.id) %>

  <!-- Show links to edit user details, go back to the user home page, or show a button to delete the account -->
  <div>
    <%= link_to "Edit user details", edit_user_path(@user) %> |
    <%= link_to "Back", users_path %>
    <% if logged_in? && is_administrator? %>
      <div style="padding-top: 50px;">
        <%= button_to "Delete Account", @user, method: :delete, class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
<% end %>