config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :categories
  resources :sources
  resources :users

  root 'home#index'
  get '/about', to: 'about#index'
  get '/search', to: 'search#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_header.html.erb
<!-- Navigation Bar -->
<nav class="navbar bg-dark border-bottom border-body navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <!-- Links for navigaton -->
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <li><a class="nav-link" href="/search">Search</a></li>
        </li>
        <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link" %>
        </li>

        <!-- Links for navigation, rendered based on if the user is logged in or not (sign up, sign in, log out) -->
        <% if !logged_in? %>
          <li class="nav-item">
            <li><%= link_to 'Sign Up', new_user_path, class:"nav-link" %></li>
          </li>
        <% end %>
        <% if !logged_in? %>
          <li class="nav-item">
          <li><%= link_to 'Sign In', login_path, class:"nav-link" %></li>
          </li>
        <% end %>
        <% if logged_in? %>
            <li class="nav-item">
            <%= button_to "Sign Out", logout_path, method: :delete, class:"btn btn-link nav-link" %>
            </li>
        <% end %>

        <!-- Dropdown menu if standard user -->
        <% if logged_in? && !is_administrator? %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu">
            <%= link_to "My Account", userhome_path, class:"dropdown-item" %>
            <%= link_to "My Quotes", your_quotes_path, class:"dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <%= link_to "Add New Quote", new_quote_path, class:"dropdown-item" %>
          </ul>
          </li>
        <% end %>

        <!-- Dropdown menu if admin user -->
        <% if logged_in? && is_administrator? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
            <ul class="dropdown-menu">
              <%= link_to "Admin Home", admin_path, class:"dropdown-item" %>
              <li><%= link_to 'Manage Users', users_path, class:"dropdown-item" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyQuote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Include Bootstrap CSS and JS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </head>

  <!-- Display the header (navigation bar) -->
  <body>
  <div class="container" style="margin-top:20px;">
  <%= render 'layouts/header' %>
    <%= yield %>
    </div>
  </body>
</html>